# Generated by Django 3.1.6 on 2021-02-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
