# Generated by Django 3.1.6 on 2021-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_list_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='list',
        ),
        migrations.AddField(
            model_name='todolist',
            name='list',
            field=models.ManyToManyField(to='profiles_api.List'),
        ),
    ]
