# Generated by Django 3.1.6 on 2021-02-05 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_remove_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.userprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
